# Change these first
owner: deerwalkrnd # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Deerwalk Classroom
    url: https://classroom.dwit.edu.np
  - name: Deerwalk Sifal School
    url: https://deerwalk.edu.np/sifal-school
  - name: Deerwalk Foods
    url: https://foods.deerwalk.edu.np
  - name: Deerwalk Institute of Technology
    url: https://deerwalk.edu.np/DWIT/
  - name: Deerwalk Education Group
    url: https://deerwalk.edu.np/
  - name: Deerwalk Dhading School
    url: https://deerwalk.edu.np/dhading-school

assignees: # Users to assign downtime issues (optional)
  - rojen11
  - itdepartmentdwit

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.deerwalk.edu.np
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Deerwalk Status
  introTitle: "Status of all applications built by Deerwalk R & D"
  introMessage: Hello
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
