# Change these first
owner: deerwalkrnd # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Deerwalk Classroom
    url: https://classroom.dwit.edu.np
  - name: Deerwalk Sifal School
    url: https://deerwalk.edu.np/sifal-school
  - name: Deerwalk Foods
    url: https://foods.deerwalk.edu.np
  - name: Deerwalk Institute of Technology
    url: https://deerwalk.edu.np/DWIT/
  - name: Deerwalk Education Group
    url: https://deerwalk.edu.np/
  - name: Deerwalk Dhading School
    url: https://deerwalk.edu.np/dhading-school
  - name: Deerwalk Training Center
    url: https://deerwalktrainingcenter.com/
  - name: Doko
    url: http://doko.dwit.edu.np/
  - name: Deerwalk Almuni
    url: https://alumni.dwit.edu.np/
  - name: Deerwalk Learning Center
    url: https://dlc.dwit.edu.np/
  - name: Deerwalk Project Hub
    url: https://projects.deerwalk.edu.np/
  - name: Deerwalk Intern Manager
    url: https://internmanager.deerwalk.edu.np/
  - name: Deerwalk Library
    url: https://dwitlibrary.deerwalk.edu.np/

assignees: # Users to assign downtime issues (optional)
  - rojen11
  - itdepartmentdwit
  - Sadikshya07

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.deerwalk.edu.np
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/deerwalkrnd/status/refs/heads/master/assets/deerwalk.svg
  name: Deerwalk Status
  introTitle: "Status of all applications built by Deerwalk R & D"
  introMessage: Hello
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
